### ISSUE TITLE
Add package website / static docs using pkgdown?

### ISSUE THREAD

**Issue by andybega** [ShanaScogin/BayesPostEst#50] opened 2019-09-10 19:04 UTC
Hi, 
how do you guys feel about adding a package website using [pkgdown](https://pkgdown.r-lib.org)? It's possible to set it up so that:

- pkgdown creates a website using the existing README, documentation, vignette
- the website is hosted as a project page on Github Pages, e.g. at something like `http://ShanaScogin.github.io/BayesPostEst`
- it's automatically built and deployed by Travis-CI as changes are made to `master`

For example, I'm using this for the package in this GitHub repo: [andybega/states](https://github.com/andybega/states) and the end result looks like this: https://www.andybeger.com/states/

Note that the pkgdown official instructions and `usethis::use_pkgdown_travis()` **do not** work with `travis-ci.com` (as opposed to the legacy `travis-ci.org`), but the setup is not that hard. Let me know if you're interested and I can provide more details.

**Comment by jkarreth** [comment] 2019-09-13 20:04
I think that would be great if/when you have the time for this! 

@ShanaScogin , your thoughts?

**Comment by ShanaScogin** [comment] 2019-09-17 00:34
Ya sounds great - this sounds like something I could do in an evening. Let me check out what Andy's linked so far and get back to everyone if I have questions.

**Comment by ShanaScogin** [comment] 2019-12-10 23:35
It's not failing currently, but I don't think the site is actually deploying correctly yet. I have the GitHub Pages sourcing from Master in the settings - perhaps this is not the way to do with Travis? @andybega - any advice?

**Comment by ShanaScogin** [comment] 2019-12-10 23:50
Ah - Never mind. It is still erroring. It seems to not error when I add the lines suggested from usethis::use_pkgdown_travis() to the travis yml, but Andy, you don't seem to have these lines in your travis yml, so not sure what's going on there yet.

**Comment by andybega** [comment] 2019-12-17 14:53
> Let me know if you're interested and I can provide more details.

Writes Andy because he just went through the process for another package but didn't write down the actual details so now, months later, he doesn't remember exactly.

Hopefully this is correct: travis will need an access token to be able to deploy the pkgdown pages to a gh-pages branch on GitHub.

1. Initialize an empty gh-pages branch; see bulled 3 at this https://pkgdown.r-lib.org/reference/deploy_site_github.html

2. Create a GH PAT https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
Mine has this name and this is the only checked setting:
<img width="1183" alt="Screen Shot 2019-12-17 at 16 42 14" src="https://user-images.githubusercontent.com/1353756/71005844-0c10ff80-20ed-11ea-83e5-f1d5435e7a74.png">

3. Add the GH PAT to travis. At https://travis-ci.com/ShanaScogin/BayesPostEst select More options > Settings, then add it as an environment variable, like this:

<img width="1352" alt="Screen Shot 2019-12-17 at 16 50 05" src="https://user-images.githubusercontent.com/1353756/71006013-51cdc800-20ed-11ea-95e2-c325a2ac38ce.png">

4. Make sure the GH repo settings are correct and will look at the gh-pages branch for the website. Example from *states*:

<img width="886" alt="Screen Shot 2019-12-17 at 16 51 06" src="https://user-images.githubusercontent.com/1353756/71006071-6dd16980-20ed-11ea-9b30-d370a983bc35.png">

**Comment by ShanaScogin** [comment] 2019-12-17 18:35
This is perfect - we actually do have a PAT with the public_repo option set up as a Travis environmental variable already, but I bet the issue is with the gh-pages. I'll work on that this week. Thanks!!

**Comment by ShanaScogin** [comment] 2020-01-11 22:48
Update: gh-pages still isn't being updated and getting travis erroring out with `invalid option "--github_token=".` Regenerated PAT and updated travis environmental variable so unsure what the problem is. Might try the second option that involves adding using travis.yml unless anyone has any other ideas?

**Comment by andybega** [comment] 2020-01-21 08:40
Based on the discussion [here](https://travis-ci.community/t/invalid-option-github-token-deploying-to-github-pages/5276), is the GITHUP_PAT environment variable set in Travis-CI?

> we actually do have a PAT with the public_repo option set up as a Travis environmental variable already

Just to confirm, the name is `GITHUB_PAT`? 

<img width="731" alt="Screen Shot 2020-01-21 at 09 38 43" src="https://user-images.githubusercontent.com/1353756/72788277-e1f1b680-3c31-11ea-8306-cfcd280692e5.png">

Weird. Looking at the log on Travis, seems that `pkgdown::build_site()` runs successfully, but can't deploy the result to `gh-pages` / GitHub.

**Comment by ShanaScogin** [comment] 2020-06-10 12:22
Hi all - Website is up! Instead of using the github pat, I ended up following this walk through (thank you @jayrobwilliams for the heads up) https://gist.github.com/gaborcsardi/68960fb01bec74d89611bb9c2b0b7e5a - I also had a github ssh issue on my side that I had to fix. I'm going to close this - specific issues about enhancing the website can be made going forward.

**Closed as completed by ShanaScogin** 2020-06-10 12:22 UTC

**Comment by andybega** [comment] 2020-06-11 11:53
Yay! BTW, GitHub has an option to add a repo website URL up top by the description, that'll make it easier to find. 

![Screen Shot 2020-06-11 at 14 52 17](https://user-images.githubusercontent.com/1353756/84382345-2850ad80-abf3-11ea-8e29-117d37bacccf.png)
